**What is Pandas?**<br>
The pandas package is the most important tool at the disposal of Data Scientists and Analysts working in Python today. The powerful machine learning and glamorous visualization tools may get all the attention, but pandas is the backbone of most data projects.

**Cheat sheet**<br>
http://http://pandas.pydata.org/Pandas_Cheat_Sheet.pdf

**A set of lesson for new pandas users**<br>
https://bitbucket.org/hrojas/learn-pandas/src/master

<img src="https://media.mnn.com/assets/images/2017/03/Panda-Eating-Bamboo-Stalk.jpg" width="700px"/>

**Import libraries**

In [1]:
import pandas as pd

**Read dataset**

In [2]:
df = pd.read_csv('../input/pokemon/Pokemon.csv')

**Print the dataset**

In [3]:
df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
9,7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False
10,8,Wartortle,Water,NaN,405,59,63,80,65,80,58,1,False
11,9,Blastoise,Water,NaN,530,79,83,100,85,105,78,1,False
12,9,BlastoiseMega Blastoise,Water,NaN,630,79,103,120,135,115,78,1,False
13,10,Caterpie,Bug,NaN,195,45,30,35,20,20,45,1,False
14,11,Metapod,Bug,NaN,205,50,20,55,25,25,30,1,False
15,12,Butterfree,Bug,Flying,395,60,45,50,90,80,70,1,False
16,13,Weedle,Bug,Poison,195,40,35,30,20,20,50,1,False
17,14,Kakuna,Bug,Poison,205,45,25,50,25,25,35,1,False
18,15,Beedrill,Bug,Poison,395,65,90,40,45,80,75,1,False
19,15,BeedrillMega Beedrill,Bug,Poison,495,65,150,40,15,80,145,1,False
20,16,Pidgey,Normal,Flying,251,40,45,40,35,35,56,1,False
21,17,Pidgeotto,Normal,Flying,349,63,60,55,50,50,71,1,False
22,18,Pidgeot,Normal,Flying,479,83,80,75,70,70,101,1,False
23,18,PidgeotMega Pidgeot,Normal,Flying,579,83,80,80,135,80,121,1,False
24,19,Rattata,Normal,NaN,253,30,56,35,25,35,72,1,False
25,20,Raticate,Normal,NaN,413,55,81,60,50,70,97,1,False
26,21,Spearow,Normal,Flying,262,40,60,30,31,31,70,1,False
27,22,Fearow,Normal,Flying,442,65,90,65,61,61,100,1,False
28,23,Ekans,Poison,NaN,288,35,60,44,40,54,55,1,False
29,24,Arbok,Poison,NaN,438,60,85,69,65,79,80,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
770,700,Sylveon,Fairy,NaN,525,95,65,65,110,130,60,6,False
771,701,Hawlucha,Fighting,Flying,500,78,92,75,74,63,118,6,False
772,702,Dedenne,Electric,Fairy,431,67,58,57,81,67,101,6,False
773,703,Carbink,Rock,Fairy,500,50,50,150,50,150,50,6,False
774,704,Goomy,Dragon,NaN,300,45,50,35,55,75,40,6,False
775,705,Sliggoo,Dragon,NaN,452,68,75,53,83,113,60,6,False
776,706,Goodra,Dragon,NaN,600,90,100,70,110,150,80,6,False
777,707,Klefki,Steel,Fairy,470,57,80,91,80,87,75,6,False
778,708,Phantump,Ghost,Grass,309,43,70,48,50,60,38,6,False
779,709,Trevenant,Ghost,Grass,474,85,110,76,65,82,56,6,False
780,710,PumpkabooAverage Size,Ghost,Grass,335,49,66,70,44,55,51,6,False
781,710,PumpkabooSmall Size,Ghost,Grass,335,44,66,70,44,55,56,6,False
782,710,PumpkabooLarge Size,Ghost,Grass,335,54,66,70,44,55,46,6,False
783,710,PumpkabooSuper Size,Ghost,Grass,335,59,66,70,44,55,41,6,False
784,711,GourgeistAverage Size,Ghost,Grass,494,65,90,122,58,75,84,6,False
785,711,GourgeistSmall Size,Ghost,Grass,494,55,85,122,58,75,99,6,False
786,711,GourgeistLarge Size,Ghost,Grass,494,75,95,122,58,75,69,6,False
787,711,GourgeistSuper Size,Ghost,Grass,494,85,100,122,58,75,54,6,False
788,712,Bergmite,Ice,NaN,304,55,69,85,32,35,28,6,False
789,713,Avalugg,Ice,NaN,514,95,117,184,44,46,28,6,False
790,714,Noibat,Flying,Dragon,245,40,30,35,45,40,55,6,False
791,715,Noivern,Flying,Dragon,535,85,70,80,97,80,123,6,False
792,716,Xerneas,Fairy,NaN,680,126,131,95,131,98,99,6,True
793,717,Yveltal,Dark,Flying,680,126,131,95,131,98,99,6,True
794,718,Zygarde50% Forme,Dragon,Ground,600,108,100,121,81,95,95,6,True
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

**Count total rows**

In [4]:
print(str(len(df)))

800

**Print first five row**

In [5]:
df.head(5)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

**Print last five rows**

In [6]:
df.tail(5)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

**Read data size**

In [7]:
df.shape

(800, 13)

**Read headers**

In [8]:
df.columns

Index(['#', 'Name', 'Type 1', 'Type 2', 'Total', 'HP', 'Attack', 'Defense',
       'Sp. Atk', 'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')

**Check the types of each column**

In [9]:
df.dtypes

#              int64
Name          object
Type 1        object
Type 2        object
Total          int64
HP             int64
Attack         int64
Defense        int64
Sp. Atk        int64
Sp. Def        int64
Speed          int64
Generation     int64
Legendary       bool
dtype: object

**Read each Columns**

In [10]:
df['Name']

0                  Bulbasaur
1                    Ivysaur
2                   Venusaur
3      VenusaurMega Venusaur
4                 Charmander
               ...
795                  Diancie
796      DiancieMega Diancie
797      HoopaHoopa Confined
798       HoopaHoopa Unbound
799                Volcanion
Name: Name, Length: 800, dtype: object

**Read first five names**

In [11]:
df['Name'][0:5]

0                Bulbasaur
1                  Ivysaur
2                 Venusaur
3    VenusaurMega Venusaur
4               Charmander
Name: Name, dtype: object

In [12]:
df[['Name', 'Generation', 'Speed']]

                      Name  Generation  Speed
0                Bulbasaur           1     45
1                  Ivysaur           1     60
2                 Venusaur           1     80
3    VenusaurMega Venusaur           1     80
4               Charmander           1     65
..                     ...         ...    ...
795                Diancie           6     50
796    DiancieMega Diancie           6    110
797    HoopaHoopa Confined           6     70
798     HoopaHoopa Unbound           6     80
799              Volcanion           6     70

[800 rows x 3 columns]

**Read each row**

In [13]:
df.iloc[1]

#                   2
Name          Ivysaur
Type 1          Grass
Type 2         Poison
Total             405
HP                 60
Attack             62
Defense            63
Sp. Atk            80
Sp. Def            80
Speed              60
Generation          1
Legendary       False
Name: 1, dtype: object

In [14]:
df.iloc[543]

#                   486
Name          Regigigas
Type 1           Normal
Type 2              NaN
Total               670
HP                  110
Attack              160
Defense             110
Sp. Atk              80
Sp. Def             110
Speed               100
Generation            4
Legendary          True
Name: 543, dtype: object

**Read multiple rows**

In [15]:
df.iloc[9:12]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
9,7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False
10,8,Wartortle,Water,NaN,405,59,63,80,65,80,58,1,False
11,9,Blastoise,Water,NaN,530,79,83,100,85,105,78,1,False

**Read a specific a value**

In [16]:
df.iloc[10,5]

59

In [17]:
df.iloc[9,2]

'Water'

**Read rows using condition**

In [18]:
df.loc[df['Type 1'] == 'Water']

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
9,7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False
10,8,Wartortle,Water,NaN,405,59,63,80,65,80,58,1,False
11,9,Blastoise,Water,NaN,530,79,83,100,85,105,78,1,False
12,9,BlastoiseMega Blastoise,Water,NaN,630,79,103,120,135,115,78,1,False
59,54,Psyduck,Water,NaN,320,50,52,48,65,50,55,1,False
60,55,Golduck,Water,NaN,500,80,82,78,95,80,85,1,False
65,60,Poliwag,Water,NaN,300,40,50,40,40,40,90,1,False
66,61,Poliwhirl,Water,NaN,385,65,65,65,50,50,90,1,False
67,62,Poliwrath,Water,Fighting,510,90,95,95,70,90,70,1,False
78,72,Tentacool,Water,Poison,335,40,40,35,50,100,70,1,False
79,73,Tentacruel,Water,Poison,515,80,70,65,80,120,100,1,False
85,79,Slowpoke,Water,Psychic,315,90,65,65,40,40,15,1,False
86,80,Slowbro,Water,Psychic,490,95,75,110,100,80,30,1,False
87,80,SlowbroMega Slowbro,Water,Psychic,590,95,75,180,130,80,30,1,False
93,86,Seel,Water,NaN,325,65,45,55,45,70,45,1,False
94,87,Dewgong,Water,Ice,475,90,70,80,70,95,70,1,False
97,90,Shellder,Water,NaN,305,30,65,100,45,25,40,1,False
98,91,Cloyster,Water,Ice,525,50,95,180,85,45,70,1,False
106,98,Krabby,Water,NaN,325,30,105,90,25,25,50,1,False
107,99,Kingler,Water,NaN,475,55,130,115,50,50,75,1,False
125,116,Horsea,Water,NaN,295,30,40,70,70,25,60,1,False
126,117,Seadra,Water,NaN,440,55,65,95,95,45,85,1,False
127,118,Goldeen,Water,NaN,320,45,67,60,35,50,63,1,False
128,119,Seaking,Water,NaN,450,80,92,65,65,80,68,1,False
129,120,Staryu,Water,NaN,340,30,45,55,70,55,85,1,False
130,121,Starmie,Water,Psychic,520,60,75,85,100,85,115,1,False
139,129,Magikarp,Water,NaN,200,20,10,55,15,20,80,1,False
140,130,Gyarados,Water,Flying,540,95,125,79,60,100,81,1,False
141,130,GyaradosMega Gyarados,Water,Dark,640,95,155,109,70,130,81,1,False
142,131,Lapras,Water,Ice,535,130,85,80,85,95,60,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
470,423,Gastrodon,Water,Ground,475,111,83,68,92,82,39,4,False
506,456,Finneon,Water,NaN,330,49,49,56,49,61,66,4,False
507,457,Lumineon,Water,NaN,460,69,69,76,69,86,91,4,False
508,458,Mantyke,Water,Flying,345,45,20,50,60,120,50,4,False
541,484,Palkia,Water,Dragon,680,90,120,100,150,120,100,4,True
547,489,Phione,Water,NaN,480,80,80,80,80,80,80,4,False
548,490,Manaphy,Water,NaN,600,100,100,100,100,100,100,4,False
560,501,Oshawott,Water,NaN,308,55,55,45,63,45,45,5,False
561,502,Dewott,Water,NaN,413,75,75,60,83,60,60,5,False
562,503,Samurott,Water,NaN,528,95,100,85,108,70,70,5,False
574,515,Panpour,Water,NaN,316,50,53,48,53,48,64,5,False
575,516,Simipour,Water,NaN,498,75,98,63,98,63,101,5,False
595,535,Tympole,Water,NaN,294,50,50,40,50,40,64,5,False
596,536,Palpitoad,Water,Ground,384,75,65,55,65,55,69,5,False
597,537,Seismitoad,Water,Ground,509,105,95,75,85,75,74,5,False
610,550,Basculin,Water,NaN,460,70,92,65,80,55,98,5,False
625,564,Tirtouga,Water,Rock,355,54,78,103,53,45,22,5,False
626,565,Carracosta,Water,Rock,495,74,108,133,83,65,32,5,False
641,580,Ducklett,Water,Flying,305,62,44,50,44,50,55,5,False
642,581,Swanna,Water,Flying,473,75,87,63,87,63,98,5,False
653,592,Frillish,Water,Ghost,335,55,40,50,65,85,40,5,False
654,593,Jellicent,Water,Ghost,480,100,60,70,85,105,60,5,False
655,594,Alomomola,Water,NaN,470,165,75,80,40,45,65,5,False
713,647,KeldeoOrdinary Forme,Water,Fighting,580,91,72,90,129,90,108,5,False
714,647,KeldeoResolute Forme,Water,Fighting,580,91,72,90,129,90,108,5,False
724,656,Froakie,Water,NaN,314,41,56,40,62,44,71,6,False
725,657,Frogadier,Water,NaN,405,54,63,52,83,56,97,6,False
726,658,Greninja,Water,Dark,530,72,95,67,103,71,122,6,False
762,692,Clauncher,Water,NaN,330,50,53,62,58,63,44,6,False
763,693,Clawitzer,Water,NaN,500,71,73,88,120,89,59,6,False

**Read rows using multiple condition**

In [19]:
df.loc[(df['Type 1'] == 'Water') & (df['Type 2'] == 'Dark')]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
141,130,GyaradosMega Gyarados,Water,Dark,640,95,155,109,70,130,81,1,False
347,318,Carvanha,Water,Dark,305,45,90,20,65,20,65,3,False
348,319,Sharpedo,Water,Dark,460,70,120,40,95,40,95,3,False
349,319,SharpedoMega Sharpedo,Water,Dark,560,70,140,70,110,65,105,3,False
374,342,Crawdaunt,Water,Dark,468,63,120,85,90,55,55,3,False
726,658,Greninja,Water,Dark,530,72,95,67,103,71,122,6,False

In [20]:
df.loc[(df['Type 1'] == 'Water') & (df['Type 2'] == 'Dark') & (df['HP'] > 60)]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
141,130,GyaradosMega Gyarados,Water,Dark,640,95,155,109,70,130,81,1,False
348,319,Sharpedo,Water,Dark,460,70,120,40,95,40,95,3,False
349,319,SharpedoMega Sharpedo,Water,Dark,560,70,140,70,110,65,105,3,False
374,342,Crawdaunt,Water,Dark,468,63,120,85,90,55,55,3,False
726,658,Greninja,Water,Dark,530,72,95,67,103,71,122,6,False

In [21]:
array = ['Dark', 'Ghost', 'Ground']
df.loc[(df['Type 1'] == 'Fire') & df['Type 2'].isin(array)]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
352,322,Numel,Fire,Ground,305,60,60,40,65,45,35,3,False
353,323,Camerupt,Fire,Ground,460,70,100,70,105,75,40,3,False
354,323,CameruptMega Camerupt,Fire,Ground,560,70,120,100,145,105,20,3,False

In [22]:
array = ['Fire', 'Water', 'Rain']
df.loc[df['Type 1'].isin(array)]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
9,7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False
10,8,Wartortle,Water,NaN,405,59,63,80,65,80,58,1,False
11,9,Blastoise,Water,NaN,530,79,83,100,85,105,78,1,False
12,9,BlastoiseMega Blastoise,Water,NaN,630,79,103,120,135,115,78,1,False
42,37,Vulpix,Fire,NaN,299,38,41,40,50,65,65,1,False
43,38,Ninetales,Fire,NaN,505,73,76,75,81,100,100,1,False
59,54,Psyduck,Water,NaN,320,50,52,48,65,50,55,1,False
60,55,Golduck,Water,NaN,500,80,82,78,95,80,85,1,False
63,58,Growlithe,Fire,NaN,350,55,70,45,70,50,60,1,False
64,59,Arcanine,Fire,NaN,555,90,110,80,100,80,95,1,False
65,60,Poliwag,Water,NaN,300,40,50,40,40,40,90,1,False
66,61,Poliwhirl,Water,NaN,385,65,65,65,50,50,90,1,False
67,62,Poliwrath,Water,Fighting,510,90,95,95,70,90,70,1,False
78,72,Tentacool,Water,Poison,335,40,40,35,50,100,70,1,False
79,73,Tentacruel,Water,Poison,515,80,70,65,80,120,100,1,False
83,77,Ponyta,Fire,NaN,410,50,85,55,65,65,90,1,False
84,78,Rapidash,Fire,NaN,500,65,100,70,80,80,105,1,False
85,79,Slowpoke,Water,Psychic,315,90,65,65,40,40,15,1,False
86,80,Slowbro,Water,Psychic,490,95,75,110,100,80,30,1,False
87,80,SlowbroMega Slowbro,Water,Psychic,590,95,75,180,130,80,30,1,False
93,86,Seel,Water,NaN,325,65,45,55,45,70,45,1,False
94,87,Dewgong,Water,Ice,475,90,70,80,70,95,70,1,False
97,90,Shellder,Water,NaN,305,30,65,100,45,25,40,1,False
98,91,Cloyster,Water,Ice,525,50,95,180,85,45,70,1,False
106,98,Krabby,Water,NaN,325,30,105,90,25,25,50,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
595,535,Tympole,Water,NaN,294,50,50,40,50,40,64,5,False
596,536,Palpitoad,Water,Ground,384,75,65,55,65,55,69,5,False
597,537,Seismitoad,Water,Ground,509,105,95,75,85,75,74,5,False
610,550,Basculin,Water,NaN,460,70,92,65,80,55,98,5,False
614,554,Darumaka,Fire,NaN,315,70,90,45,15,45,50,5,False
615,555,DarmanitanStandard Mode,Fire,NaN,480,105,140,55,30,55,95,5,False
616,555,DarmanitanZen Mode,Fire,Psychic,540,105,30,105,140,105,55,5,False
625,564,Tirtouga,Water,Rock,355,54,78,103,53,45,22,5,False
626,565,Carracosta,Water,Rock,495,74,108,133,83,65,32,5,False
641,580,Ducklett,Water,Flying,305,62,44,50,44,50,55,5,False
642,581,Swanna,Water,Flying,473,75,87,63,87,63,98,5,False
653,592,Frillish,Water,Ghost,335,55,40,50,65,85,40,5,False
654,593,Jellicent,Water,Ghost,480,100,60,70,85,105,60,5,False
655,594,Alomomola,Water,NaN,470,165,75,80,40,45,65,5,False
692,631,Heatmor,Fire,NaN,484,85,97,66,105,66,65,5,False
713,647,KeldeoOrdinary Forme,Water,Fighting,580,91,72,90,129,90,108,5,False
714,647,KeldeoResolute Forme,Water,Fighting,580,91,72,90,129,90,108,5,False
721,653,Fennekin,Fire,NaN,307,40,45,40,62,60,60,6,False
722,654,Braixen,Fire,NaN,409,59,59,58,90,70,73,6,False
723,655,Delphox,Fire,Psychic,534,75,69,72,114,100,104,6,False
724,656,Froakie,Water,NaN,314,41,56,40,62,44,71,6,False
725,657,Frogadier,Water,NaN,405,54,63,52,83,56,97,6,False
726,658,Greninja,Water,Dark,530,72,95,67,103,71,122,6,False
730,662,Fletchinder,Fire,Flying,382,62,73,55,56,52,84,6,False
731,663,Talonflame,Fire,Flying,499,78,81,71,74,69,126,6,False
735,667,Litleo,Fire,Normal,369,62,50,58,73,54,72,6,False
736,668,Pyroar,Fire,Normal,507,86,68,72,109,66,106,6,False
762,692,Clauncher,Water,NaN,330,50,53,62,58,63,44,6,False
763,693,Clawitzer,Water,NaN,500,71,73,88,120,89,59,6,False
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

**Describing data**

In [23]:
df.describe()

,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
count,800.000000,800.00000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000
mean,362.813750,435.10250,69.258750,79.001250,73.842500,72.820000,71.902500,68.277500,3.32375
std,208.343798,119.96304,25.534669,32.457366,31.183501,32.722294,27.828916,29.060474,1.66129
min,1.000000,180.00000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.00000
25%,184.750000,330.00000,50.000000,55.000000,50.000000,49.750000,50.000000,45.000000,2.00000
50%,364.500000,450.00000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.00000
75%,539.250000,515.00000,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.00000
max,721.000000,780.00000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.00000

**Sorting data**

In [24]:
df.sort_values('Name')

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
510,460,Abomasnow,Grass,Ice,494,90,92,75,92,85,60,4,False
511,460,AbomasnowMega Abomasnow,Grass,Ice,594,90,132,105,132,105,30,4,False
68,63,Abra,Psychic,NaN,310,25,20,15,105,55,90,1,False
392,359,Absol,Dark,NaN,465,65,130,60,75,60,75,3,False
393,359,AbsolMega Absol,Dark,NaN,565,65,150,60,115,60,115,3,False
678,617,Accelgor,Bug,NaN,495,80,70,40,100,60,145,5,False
750,681,AegislashBlade Forme,Steel,Ghost,520,60,150,50,150,50,60,6,False
751,681,AegislashShield Forme,Steel,Ghost,520,60,50,150,50,150,60,6,False
153,142,Aerodactyl,Rock,Flying,515,80,105,65,60,75,130,1,False
154,142,AerodactylMega Aerodactyl,Rock,Flying,615,80,135,85,70,95,150,1,False
332,306,Aggron,Steel,Rock,530,70,110,180,60,60,50,3,False
333,306,AggronMega Aggron,Steel,NaN,630,70,140,230,60,80,50,3,False
205,190,Aipom,Normal,NaN,360,55,70,55,40,55,85,2,False
70,65,Alakazam,Psychic,NaN,500,55,50,45,135,95,120,1,False
71,65,AlakazamMega Alakazam,Psychic,NaN,590,55,50,65,175,95,150,1,False
655,594,Alomomola,Water,NaN,470,165,75,80,40,45,65,5,False
365,334,Altaria,Dragon,Flying,490,75,70,90,70,105,80,3,False
366,334,AltariaMega Altaria,Dragon,Fairy,590,75,110,110,110,105,80,3,False
768,698,Amaura,Rock,Ice,362,77,59,50,67,63,46,6,False
471,424,Ambipom,Normal,NaN,482,75,100,66,60,66,115,4,False
652,591,Amoonguss,Grass,Poison,464,114,85,70,85,80,30,5,False
195,181,Ampharos,Electric,NaN,510,90,75,85,115,90,55,2,False
196,181,AmpharosMega Ampharos,Electric,Dragon,610,90,95,105,165,110,45,2,False
379,347,Anorith,Rock,Bug,355,45,95,50,40,50,75,3,False
29,24,Arbok,Poison,NaN,438,60,85,69,65,79,80,1,False
64,59,Arcanine,Fire,NaN,555,90,110,80,100,80,95,1,False
552,493,Arceus,Normal,NaN,720,120,120,120,120,120,120,4,True
627,566,Archen,Rock,Flying,401,55,112,45,74,45,70,5,False
628,567,Archeops,Rock,Flying,567,75,140,65,112,65,110,5,False
182,168,Ariados,Bug,Poison,390,70,90,70,60,60,40,2,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
607,547,Whimsicott,Grass,Fairy,480,60,67,85,77,75,116,5,False
604,544,Whirlipede,Bug,Poison,360,40,55,99,40,79,47,5,False
372,340,Whiscash,Water,Ground,468,110,78,73,76,71,60,3,False
317,293,Whismur,Normal,NaN,240,64,51,23,51,23,28,3,False
45,40,Wigglytuff,Normal,Fairy,435,140,70,45,85,50,45,1,False
301,278,Wingull,Water,Flying,270,40,30,30,55,30,85,3,False
217,202,Wobbuffet,Psychic,NaN,405,190,33,58,33,58,33,2,False
586,527,Woobat,Psychic,Flying,313,55,45,43,55,43,72,5,False
209,194,Wooper,Water,Ground,210,55,45,45,25,25,15,2,False
458,413,WormadamPlant Cloak,Bug,Grass,424,60,59,85,79,105,36,4,False
459,413,WormadamSandy Cloak,Bug,Ground,424,60,79,105,59,85,36,4,False
460,413,WormadamTrash Cloak,Bug,Steel,424,60,69,95,69,95,36,4,False
288,265,Wurmple,Bug,NaN,195,45,45,35,20,30,20,3,False
394,360,Wynaut,Psychic,NaN,260,95,23,48,23,48,23,3,False
192,178,Xatu,Psychic,Flying,470,65,75,70,95,70,95,2,False
792,716,Xerneas,Fairy,NaN,680,126,131,95,131,98,99,6,True
623,562,Yamask,Ghost,NaN,303,38,30,85,55,65,30,5,False
208,193,Yanma,Bug,Flying,390,65,65,45,75,45,95,2,False
520,469,Yanmega,Bug,Flying,515,86,76,86,116,56,95,4,False
793,717,Yveltal,Dark,Flying,680,126,131,95,131,98,99,6,True
367,335,Zangoose,Normal,NaN,458,73,115,60,60,60,90,3,False
157,145,Zapdos,Electric,Flying,580,90,90,85,125,90,100,1,True
582,523,Zebstrika,Electric,NaN,497,75,100,63,80,63,116,5,False
707,644,Zekrom,Dragon,Electric,680,100,150,120,120,100,90,5,True
286,263,Zigzagoon,Normal,NaN,240,38,30,41,30,41,60,3,False
632,571,Zoroark,Dark,NaN,510,60,105,60,120,60,105,5,False
631,570,Zorua,Dark,NaN,330,40,65,40,80,40,65,5,False
46,41,Zubat,Poison,Flying,245,40,45,35,30,40,55,1,False
695,634,Zweilous,Dark,Dragon,420,72,85,70,65,70,58,5,False
794,718,Zygarde50% Forme,Dragon,Ground,600,108,100,121,81,95,95,6,True

**Sorting data using multiple columns**

In [25]:
df.sort_values(['Name', 'HP', 'Generation'])

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
510,460,Abomasnow,Grass,Ice,494,90,92,75,92,85,60,4,False
511,460,AbomasnowMega Abomasnow,Grass,Ice,594,90,132,105,132,105,30,4,False
68,63,Abra,Psychic,NaN,310,25,20,15,105,55,90,1,False
392,359,Absol,Dark,NaN,465,65,130,60,75,60,75,3,False
393,359,AbsolMega Absol,Dark,NaN,565,65,150,60,115,60,115,3,False
678,617,Accelgor,Bug,NaN,495,80,70,40,100,60,145,5,False
750,681,AegislashBlade Forme,Steel,Ghost,520,60,150,50,150,50,60,6,False
751,681,AegislashShield Forme,Steel,Ghost,520,60,50,150,50,150,60,6,False
153,142,Aerodactyl,Rock,Flying,515,80,105,65,60,75,130,1,False
154,142,AerodactylMega Aerodactyl,Rock,Flying,615,80,135,85,70,95,150,1,False
332,306,Aggron,Steel,Rock,530,70,110,180,60,60,50,3,False
333,306,AggronMega Aggron,Steel,NaN,630,70,140,230,60,80,50,3,False
205,190,Aipom,Normal,NaN,360,55,70,55,40,55,85,2,False
70,65,Alakazam,Psychic,NaN,500,55,50,45,135,95,120,1,False
71,65,AlakazamMega Alakazam,Psychic,NaN,590,55,50,65,175,95,150,1,False
655,594,Alomomola,Water,NaN,470,165,75,80,40,45,65,5,False
365,334,Altaria,Dragon,Flying,490,75,70,90,70,105,80,3,False
366,334,AltariaMega Altaria,Dragon,Fairy,590,75,110,110,110,105,80,3,False
768,698,Amaura,Rock,Ice,362,77,59,50,67,63,46,6,False
471,424,Ambipom,Normal,NaN,482,75,100,66,60,66,115,4,False
652,591,Amoonguss,Grass,Poison,464,114,85,70,85,80,30,5,False
195,181,Ampharos,Electric,NaN,510,90,75,85,115,90,55,2,False
196,181,AmpharosMega Ampharos,Electric,Dragon,610,90,95,105,165,110,45,2,False
379,347,Anorith,Rock,Bug,355,45,95,50,40,50,75,3,False
29,24,Arbok,Poison,NaN,438,60,85,69,65,79,80,1,False
64,59,Arcanine,Fire,NaN,555,90,110,80,100,80,95,1,False
552,493,Arceus,Normal,NaN,720,120,120,120,120,120,120,4,True
627,566,Archen,Rock,Flying,401,55,112,45,74,45,70,5,False
628,567,Archeops,Rock,Flying,567,75,140,65,112,65,110,5,False
182,168,Ariados,Bug,Poison,390,70,90,70,60,60,40,2,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
607,547,Whimsicott,Grass,Fairy,480,60,67,85,77,75,116,5,False
604,544,Whirlipede,Bug,Poison,360,40,55,99,40,79,47,5,False
372,340,Whiscash,Water,Ground,468,110,78,73,76,71,60,3,False
317,293,Whismur,Normal,NaN,240,64,51,23,51,23,28,3,False
45,40,Wigglytuff,Normal,Fairy,435,140,70,45,85,50,45,1,False
301,278,Wingull,Water,Flying,270,40,30,30,55,30,85,3,False
217,202,Wobbuffet,Psychic,NaN,405,190,33,58,33,58,33,2,False
586,527,Woobat,Psychic,Flying,313,55,45,43,55,43,72,5,False
209,194,Wooper,Water,Ground,210,55,45,45,25,25,15,2,False
458,413,WormadamPlant Cloak,Bug,Grass,424,60,59,85,79,105,36,4,False
459,413,WormadamSandy Cloak,Bug,Ground,424,60,79,105,59,85,36,4,False
460,413,WormadamTrash Cloak,Bug,Steel,424,60,69,95,69,95,36,4,False
288,265,Wurmple,Bug,NaN,195,45,45,35,20,30,20,3,False
394,360,Wynaut,Psychic,NaN,260,95,23,48,23,48,23,3,False
192,178,Xatu,Psychic,Flying,470,65,75,70,95,70,95,2,False
792,716,Xerneas,Fairy,NaN,680,126,131,95,131,98,99,6,True
623,562,Yamask,Ghost,NaN,303,38,30,85,55,65,30,5,False
208,193,Yanma,Bug,Flying,390,65,65,45,75,45,95,2,False
520,469,Yanmega,Bug,Flying,515,86,76,86,116,56,95,4,False
793,717,Yveltal,Dark,Flying,680,126,131,95,131,98,99,6,True
367,335,Zangoose,Normal,NaN,458,73,115,60,60,60,90,3,False
157,145,Zapdos,Electric,Flying,580,90,90,85,125,90,100,1,True
582,523,Zebstrika,Electric,NaN,497,75,100,63,80,63,116,5,False
707,644,Zekrom,Dragon,Electric,680,100,150,120,120,100,90,5,True
286,263,Zigzagoon,Normal,NaN,240,38,30,41,30,41,60,3,False
632,571,Zoroark,Dark,NaN,510,60,105,60,120,60,105,5,False
631,570,Zorua,Dark,NaN,330,40,65,40,80,40,65,5,False
46,41,Zubat,Poison,Flying,245,40,45,35,30,40,55,1,False
695,634,Zweilous,Dark,Dragon,420,72,85,70,65,70,58,5,False
794,718,Zygarde50% Forme,Dragon,Ground,600,108,100,121,81,95,95,6,True

**Sorting data into dscending order**

In [26]:
df.sort_values('Name', ascending = False)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
794,718,Zygarde50% Forme,Dragon,Ground,600,108,100,121,81,95,95,6,True
695,634,Zweilous,Dark,Dragon,420,72,85,70,65,70,58,5,False
46,41,Zubat,Poison,Flying,245,40,45,35,30,40,55,1,False
631,570,Zorua,Dark,NaN,330,40,65,40,80,40,65,5,False
632,571,Zoroark,Dark,NaN,510,60,105,60,120,60,105,5,False
286,263,Zigzagoon,Normal,NaN,240,38,30,41,30,41,60,3,False
707,644,Zekrom,Dragon,Electric,680,100,150,120,120,100,90,5,True
582,523,Zebstrika,Electric,NaN,497,75,100,63,80,63,116,5,False
157,145,Zapdos,Electric,Flying,580,90,90,85,125,90,100,1,True
367,335,Zangoose,Normal,NaN,458,73,115,60,60,60,90,3,False
793,717,Yveltal,Dark,Flying,680,126,131,95,131,98,99,6,True
520,469,Yanmega,Bug,Flying,515,86,76,86,116,56,95,4,False
208,193,Yanma,Bug,Flying,390,65,65,45,75,45,95,2,False
623,562,Yamask,Ghost,NaN,303,38,30,85,55,65,30,5,False
792,716,Xerneas,Fairy,NaN,680,126,131,95,131,98,99,6,True
192,178,Xatu,Psychic,Flying,470,65,75,70,95,70,95,2,False
394,360,Wynaut,Psychic,NaN,260,95,23,48,23,48,23,3,False
288,265,Wurmple,Bug,NaN,195,45,45,35,20,30,20,3,False
460,413,WormadamTrash Cloak,Bug,Steel,424,60,69,95,69,95,36,4,False
459,413,WormadamSandy Cloak,Bug,Ground,424,60,79,105,59,85,36,4,False
458,413,WormadamPlant Cloak,Bug,Grass,424,60,59,85,79,105,36,4,False
209,194,Wooper,Water,Ground,210,55,45,45,25,25,15,2,False
586,527,Woobat,Psychic,Flying,313,55,45,43,55,43,72,5,False
217,202,Wobbuffet,Psychic,NaN,405,190,33,58,33,58,33,2,False
301,278,Wingull,Water,Flying,270,40,30,30,55,30,85,3,False
45,40,Wigglytuff,Normal,Fairy,435,140,70,45,85,50,45,1,False
317,293,Whismur,Normal,NaN,240,64,51,23,51,23,28,3,False
372,340,Whiscash,Water,Ground,468,110,78,73,76,71,60,3,False
604,544,Whirlipede,Bug,Poison,360,40,55,99,40,79,47,5,False
607,547,Whimsicott,Grass,Fairy,480,60,67,85,77,75,116,5,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
182,168,Ariados,Bug,Poison,390,70,90,70,60,60,40,2,False
628,567,Archeops,Rock,Flying,567,75,140,65,112,65,110,5,False
627,566,Archen,Rock,Flying,401,55,112,45,74,45,70,5,False
552,493,Arceus,Normal,NaN,720,120,120,120,120,120,120,4,True
64,59,Arcanine,Fire,NaN,555,90,110,80,100,80,95,1,False
29,24,Arbok,Poison,NaN,438,60,85,69,65,79,80,1,False
379,347,Anorith,Rock,Bug,355,45,95,50,40,50,75,3,False
196,181,AmpharosMega Ampharos,Electric,Dragon,610,90,95,105,165,110,45,2,False
195,181,Ampharos,Electric,NaN,510,90,75,85,115,90,55,2,False
652,591,Amoonguss,Grass,Poison,464,114,85,70,85,80,30,5,False
471,424,Ambipom,Normal,NaN,482,75,100,66,60,66,115,4,False
768,698,Amaura,Rock,Ice,362,77,59,50,67,63,46,6,False
366,334,AltariaMega Altaria,Dragon,Fairy,590,75,110,110,110,105,80,3,False
365,334,Altaria,Dragon,Flying,490,75,70,90,70,105,80,3,False
655,594,Alomomola,Water,NaN,470,165,75,80,40,45,65,5,False
71,65,AlakazamMega Alakazam,Psychic,NaN,590,55,50,65,175,95,150,1,False
70,65,Alakazam,Psychic,NaN,500,55,50,45,135,95,120,1,False
205,190,Aipom,Normal,NaN,360,55,70,55,40,55,85,2,False
333,306,AggronMega Aggron,Steel,NaN,630,70,140,230,60,80,50,3,False
332,306,Aggron,Steel,Rock,530,70,110,180,60,60,50,3,False
154,142,AerodactylMega Aerodactyl,Rock,Flying,615,80,135,85,70,95,150,1,False
153,142,Aerodactyl,Rock,Flying,515,80,105,65,60,75,130,1,False
751,681,AegislashShield Forme,Steel,Ghost,520,60,50,150,50,150,60,6,False
750,681,AegislashBlade Forme,Steel,Ghost,520,60,150,50,150,50,60,6,False
678,617,Accelgor,Bug,NaN,495,80,70,40,100,60,145,5,False
393,359,AbsolMega Absol,Dark,NaN,565,65,150,60,115,60,115,3,False
392,359,Absol,Dark,NaN,465,65,130,60,75,60,75,3,False
68,63,Abra,Psychic,NaN,310,25,20,15,105,55,90,1,False
511,460,AbomasnowMega Abomasnow,Grass,Ice,594,90,132,105,132,105,30,4,False
510,460,Abomasnow,Grass,Ice,494,90,92,75,92,85,60,4,False

In [27]:
df.sort_values(['Name', 'Type 1', 'Type 2'], ascending = [1, 0, 1])

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
510,460,Abomasnow,Grass,Ice,494,90,92,75,92,85,60,4,False
511,460,AbomasnowMega Abomasnow,Grass,Ice,594,90,132,105,132,105,30,4,False
68,63,Abra,Psychic,NaN,310,25,20,15,105,55,90,1,False
392,359,Absol,Dark,NaN,465,65,130,60,75,60,75,3,False
393,359,AbsolMega Absol,Dark,NaN,565,65,150,60,115,60,115,3,False
678,617,Accelgor,Bug,NaN,495,80,70,40,100,60,145,5,False
750,681,AegislashBlade Forme,Steel,Ghost,520,60,150,50,150,50,60,6,False
751,681,AegislashShield Forme,Steel,Ghost,520,60,50,150,50,150,60,6,False
153,142,Aerodactyl,Rock,Flying,515,80,105,65,60,75,130,1,False
154,142,AerodactylMega Aerodactyl,Rock,Flying,615,80,135,85,70,95,150,1,False
332,306,Aggron,Steel,Rock,530,70,110,180,60,60,50,3,False
333,306,AggronMega Aggron,Steel,NaN,630,70,140,230,60,80,50,3,False
205,190,Aipom,Normal,NaN,360,55,70,55,40,55,85,2,False
70,65,Alakazam,Psychic,NaN,500,55,50,45,135,95,120,1,False
71,65,AlakazamMega Alakazam,Psychic,NaN,590,55,50,65,175,95,150,1,False
655,594,Alomomola,Water,NaN,470,165,75,80,40,45,65,5,False
365,334,Altaria,Dragon,Flying,490,75,70,90,70,105,80,3,False
366,334,AltariaMega Altaria,Dragon,Fairy,590,75,110,110,110,105,80,3,False
768,698,Amaura,Rock,Ice,362,77,59,50,67,63,46,6,False
471,424,Ambipom,Normal,NaN,482,75,100,66,60,66,115,4,False
652,591,Amoonguss,Grass,Poison,464,114,85,70,85,80,30,5,False
195,181,Ampharos,Electric,NaN,510,90,75,85,115,90,55,2,False
196,181,AmpharosMega Ampharos,Electric,Dragon,610,90,95,105,165,110,45,2,False
379,347,Anorith,Rock,Bug,355,45,95,50,40,50,75,3,False
29,24,Arbok,Poison,NaN,438,60,85,69,65,79,80,1,False
64,59,Arcanine,Fire,NaN,555,90,110,80,100,80,95,1,False
552,493,Arceus,Normal,NaN,720,120,120,120,120,120,120,4,True
627,566,Archen,Rock,Flying,401,55,112,45,74,45,70,5,False
628,567,Archeops,Rock,Flying,567,75,140,65,112,65,110,5,False
182,168,Ariados,Bug,Poison,390,70,90,70,60,60,40,2,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
607,547,Whimsicott,Grass,Fairy,480,60,67,85,77,75,116,5,False
604,544,Whirlipede,Bug,Poison,360,40,55,99,40,79,47,5,False
372,340,Whiscash,Water,Ground,468,110,78,73,76,71,60,3,False
317,293,Whismur,Normal,NaN,240,64,51,23,51,23,28,3,False
45,40,Wigglytuff,Normal,Fairy,435,140,70,45,85,50,45,1,False
301,278,Wingull,Water,Flying,270,40,30,30,55,30,85,3,False
217,202,Wobbuffet,Psychic,NaN,405,190,33,58,33,58,33,2,False
586,527,Woobat,Psychic,Flying,313,55,45,43,55,43,72,5,False
209,194,Wooper,Water,Ground,210,55,45,45,25,25,15,2,False
458,413,WormadamPlant Cloak,Bug,Grass,424,60,59,85,79,105,36,4,False
459,413,WormadamSandy Cloak,Bug,Ground,424,60,79,105,59,85,36,4,False
460,413,WormadamTrash Cloak,Bug,Steel,424,60,69,95,69,95,36,4,False
288,265,Wurmple,Bug,NaN,195,45,45,35,20,30,20,3,False
394,360,Wynaut,Psychic,NaN,260,95,23,48,23,48,23,3,False
192,178,Xatu,Psychic,Flying,470,65,75,70,95,70,95,2,False
792,716,Xerneas,Fairy,NaN,680,126,131,95,131,98,99,6,True
623,562,Yamask,Ghost,NaN,303,38,30,85,55,65,30,5,False
208,193,Yanma,Bug,Flying,390,65,65,45,75,45,95,2,False
520,469,Yanmega,Bug,Flying,515,86,76,86,116,56,95,4,False
793,717,Yveltal,Dark,Flying,680,126,131,95,131,98,99,6,True
367,335,Zangoose,Normal,NaN,458,73,115,60,60,60,90,3,False
157,145,Zapdos,Electric,Flying,580,90,90,85,125,90,100,1,True
582,523,Zebstrika,Electric,NaN,497,75,100,63,80,63,116,5,False
707,644,Zekrom,Dragon,Electric,680,100,150,120,120,100,90,5,True
286,263,Zigzagoon,Normal,NaN,240,38,30,41,30,41,60,3,False
632,571,Zoroark,Dark,NaN,510,60,105,60,120,60,105,5,False
631,570,Zorua,Dark,NaN,330,40,65,40,80,40,65,5,False
46,41,Zubat,Poison,Flying,245,40,45,35,30,40,55,1,False
695,634,Zweilous,Dark,Dragon,420,72,85,70,65,70,58,5,False
794,718,Zygarde50% Forme,Dragon,Ground,600,108,100,121,81,95,95,6,True

**Making changes to the data**

In [28]:
df.head(5)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

In [29]:
df['Sum'] = df['Total'] + df['HP'] + df['Attack']
df.head(5)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Sum
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,412
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,527
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,687
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,805
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,400

In [30]:
df['Mul'] = df['HP'] * df['Attack']
df.tail(5)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Sum,Mul
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True,750,5000
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True,910,8000
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True,790,8800
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True,920,12800
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True,790,8800

**Drop a column**

In [31]:
df.columns

Index(['#', 'Name', 'Type 1', 'Type 2', 'Total', 'HP', 'Attack', 'Defense',
       'Sp. Atk', 'Sp. Def', 'Speed', 'Generation', 'Legendary', 'Sum', 'Mul'],
      dtype='object')

In [32]:
df = df.drop(columns=['Sum'])
df.head(3)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Mul
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,2205
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,3720
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,6560

**Alternative way to sum columns**

In [33]:
df['Sum2'] = df.iloc[:, 4:8].sum(axis=1)
df.head(3)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Mul,Sum2
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,2205,461
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,3720,590
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,6560,770

**Drop multiple columns**

In [34]:
df = df.drop(columns=['Sum2', 'Mul'])
df.head(5)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

**Filtering data**

**Sreach rows using valus**

In [35]:
df.loc[df['Type 1'] == 'Dark']

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
212,197,Umbreon,Dark,NaN,525,95,65,110,60,130,65,2,False
213,198,Murkrow,Dark,Flying,405,60,85,42,85,42,91,2,False
233,215,Sneasel,Dark,Ice,430,55,95,55,35,75,115,2,False
246,228,Houndour,Dark,Fire,330,45,60,30,80,50,65,2,False
247,229,Houndoom,Dark,Fire,500,75,90,50,110,80,95,2,False
248,229,HoundoomMega Houndoom,Dark,Fire,600,75,90,90,140,90,115,2,False
284,261,Poochyena,Dark,NaN,220,35,55,35,30,30,35,3,False
285,262,Mightyena,Dark,NaN,420,70,90,70,60,60,70,3,False
326,302,Sableye,Dark,Ghost,380,50,75,75,65,65,50,3,False
327,302,SableyeMega Sableye,Dark,Ghost,480,50,85,125,85,115,20,3,False
392,359,Absol,Dark,NaN,465,65,130,60,75,60,75,3,False
393,359,AbsolMega Absol,Dark,NaN,565,65,150,60,115,60,115,3,False
478,430,Honchkrow,Dark,Flying,505,100,125,52,105,52,71,4,False
512,461,Weavile,Dark,Ice,510,70,120,65,45,85,125,4,False
549,491,Darkrai,Dark,NaN,600,70,90,90,135,90,125,4,True
568,509,Purrloin,Dark,NaN,281,41,50,37,50,37,66,5,False
569,510,Liepard,Dark,NaN,446,64,88,50,88,50,106,5,False
620,559,Scraggy,Dark,Fighting,348,50,75,70,35,70,48,5,False
621,560,Scrafty,Dark,Fighting,488,65,90,115,45,115,58,5,False
631,570,Zorua,Dark,NaN,330,40,65,40,80,40,65,5,False
632,571,Zoroark,Dark,NaN,510,60,105,60,120,60,105,5,False
685,624,Pawniard,Dark,Steel,340,45,85,70,40,40,60,5,False
686,625,Bisharp,Dark,Steel,490,65,125,100,60,70,70,5,False
690,629,Vullaby,Dark,Flying,370,70,55,75,45,65,60,5,False
691,630,Mandibuzz,Dark,Flying,510,110,65,105,55,95,80,5,False
694,633,Deino,Dark,Dragon,300,52,65,50,45,50,38,5,False
695,634,Zweilous,Dark,Dragon,420,72,85,70,65,70,58,5,False
696,635,Hydreigon,Dark,Dragon,600,92,105,90,125,90,98,5,False
756,686,Inkay,Dark,Psychic,288,53,54,53,37,46,45,6,False
757,687,Malamar,Dark,Psychic,482,86,92,88,68,75,73,6,False
793,717,Yveltal,Dark,Flying,680,126,131,95,131,98,99,6,True

In [36]:
df.loc[df['Type 2'] == 'Fire']

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
246,228,Houndour,Dark,Fire,330,45,60,30,80,50,65,2,False
247,229,Houndoom,Dark,Fire,500,75,90,50,110,80,95,2,False
248,229,HoundoomMega Houndoom,Dark,Fire,600,75,90,90,140,90,115,2,False
424,383,GroudonPrimal Groudon,Ground,Fire,770,100,180,160,150,90,90,3,True
532,479,RotomHeat Rotom,Electric,Fire,520,50,65,107,105,107,86,4,False
553,494,Victini,Psychic,Fire,600,100,100,100,100,100,100,5,True
668,607,Litwick,Ghost,Fire,275,50,30,55,65,55,20,5,False
669,608,Lampent,Ghost,Fire,370,60,40,60,95,60,55,5,False
670,609,Chandelure,Ghost,Fire,520,60,55,90,145,90,80,5,False
697,636,Larvesta,Bug,Fire,360,55,85,55,50,55,60,5,False
698,637,Volcarona,Bug,Fire,550,85,60,65,135,105,100,5,False
706,643,Reshiram,Dragon,Fire,680,100,120,100,150,120,90,5,True

**Search rows using multiple values**

In [37]:
df.loc[(df['Type 1'] == 'Bug') & (df['Type 2'] == 'Fire')]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
697,636,Larvesta,Bug,Fire,360,55,85,55,50,55,60,5,False
698,637,Volcarona,Bug,Fire,550,85,60,65,135,105,100,5,False

In [38]:
df.loc[(df['Type 1'] == 'Dark') & (df['Type 2'] == 'Fire') & (df['HP'] > 20)]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
246,228,Houndour,Dark,Fire,330,45,60,30,80,50,65,2,False
247,229,Houndoom,Dark,Fire,500,75,90,50,110,80,95,2,False
248,229,HoundoomMega Houndoom,Dark,Fire,600,75,90,90,140,90,115,2,False

In [39]:
df.loc[((df['Type 1'] == 'Dark') | (df['Type 2'] == 'Dark')) & (df['Total'] > 500)]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
141,130,GyaradosMega Gyarados,Water,Dark,640,95,155,109,70,130,81,1,False
212,197,Umbreon,Dark,NaN,525,95,65,110,60,130,65,2,False
248,229,HoundoomMega Houndoom,Dark,Fire,600,75,90,90,140,90,115,2,False
267,248,Tyranitar,Rock,Dark,600,100,134,110,95,100,61,2,False
268,248,TyranitarMega Tyranitar,Rock,Dark,700,100,164,150,95,120,71,2,False
349,319,SharpedoMega Sharpedo,Water,Dark,560,70,140,70,110,65,105,3,False
393,359,AbsolMega Absol,Dark,NaN,565,65,150,60,115,60,115,3,False
478,430,Honchkrow,Dark,Flying,505,100,125,52,105,52,71,4,False
512,461,Weavile,Dark,Ice,510,70,120,65,45,85,125,4,False
549,491,Darkrai,Dark,NaN,600,70,90,90,135,90,125,4,True
613,553,Krookodile,Ground,Dark,519,95,117,80,65,70,92,5,False
632,571,Zoroark,Dark,NaN,510,60,105,60,120,60,105,5,False
691,630,Mandibuzz,Dark,Flying,510,110,65,105,55,95,80,5,False
696,635,Hydreigon,Dark,Dragon,600,92,105,90,125,90,98,5,False
726,658,Greninja,Water,Dark,530,72,95,67,103,71,122,6,False
793,717,Yveltal,Dark,Flying,680,126,131,95,131,98,99,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True

**Making new csv file**

In [40]:
df_new = df.loc[(df['Type 1'] == 'Dark') & (df['Type 2'] == 'Fire') & (df['HP'] > 10)]
df_new
#df_new.to_csv('New Pokemon')

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
246,228,Houndour,Dark,Fire,330,45,60,30,80,50,65,2,False
247,229,Houndoom,Dark,Fire,500,75,90,50,110,80,95,2,False
248,229,HoundoomMega Houndoom,Dark,Fire,600,75,90,90,140,90,115,2,False

In [41]:
df_new1 = df.loc[(df['Type 1'] == 'Dark') | (df['Defense'] >= 600)]
df_new1

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
212,197,Umbreon,Dark,NaN,525,95,65,110,60,130,65,2,False
213,198,Murkrow,Dark,Flying,405,60,85,42,85,42,91,2,False
233,215,Sneasel,Dark,Ice,430,55,95,55,35,75,115,2,False
246,228,Houndour,Dark,Fire,330,45,60,30,80,50,65,2,False
247,229,Houndoom,Dark,Fire,500,75,90,50,110,80,95,2,False
248,229,HoundoomMega Houndoom,Dark,Fire,600,75,90,90,140,90,115,2,False
284,261,Poochyena,Dark,NaN,220,35,55,35,30,30,35,3,False
285,262,Mightyena,Dark,NaN,420,70,90,70,60,60,70,3,False
326,302,Sableye,Dark,Ghost,380,50,75,75,65,65,50,3,False
327,302,SableyeMega Sableye,Dark,Ghost,480,50,85,125,85,115,20,3,False
392,359,Absol,Dark,NaN,465,65,130,60,75,60,75,3,False
393,359,AbsolMega Absol,Dark,NaN,565,65,150,60,115,60,115,3,False
478,430,Honchkrow,Dark,Flying,505,100,125,52,105,52,71,4,False
512,461,Weavile,Dark,Ice,510,70,120,65,45,85,125,4,False
549,491,Darkrai,Dark,NaN,600,70,90,90,135,90,125,4,True
568,509,Purrloin,Dark,NaN,281,41,50,37,50,37,66,5,False
569,510,Liepard,Dark,NaN,446,64,88,50,88,50,106,5,False
620,559,Scraggy,Dark,Fighting,348,50,75,70,35,70,48,5,False
621,560,Scrafty,Dark,Fighting,488,65,90,115,45,115,58,5,False
631,570,Zorua,Dark,NaN,330,40,65,40,80,40,65,5,False
632,571,Zoroark,Dark,NaN,510,60,105,60,120,60,105,5,False
685,624,Pawniard,Dark,Steel,340,45,85,70,40,40,60,5,False
686,625,Bisharp,Dark,Steel,490,65,125,100,60,70,70,5,False
690,629,Vullaby,Dark,Flying,370,70,55,75,45,65,60,5,False
691,630,Mandibuzz,Dark,Flying,510,110,65,105,55,95,80,5,False
694,633,Deino,Dark,Dragon,300,52,65,50,45,50,38,5,False
695,634,Zweilous,Dark,Dragon,420,72,85,70,65,70,58,5,False
696,635,Hydreigon,Dark,Dragon,600,92,105,90,125,90,98,5,False
756,686,Inkay,Dark,Psychic,288,53,54,53,37,46,45,6,False
757,687,Malamar,Dark,Psychic,482,86,92,88,68,75,73,6,False
793,717,Yveltal,Dark,Flying,680,126,131,95,131,98,99,6,True

**Searchibg by string values**

In [42]:
df.loc[df['Name'].str.contains('Houndoom')]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
247,229,Houndoom,Dark,Fire,500,75,90,50,110,80,95,2,False
248,229,HoundoomMega Houndoom,Dark,Fire,600,75,90,90,140,90,115,2,False

In [43]:
df.loc[df['Name'].str.contains('ye')]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
284,261,Poochyena,Dark,NaN,220,35,55,35,30,30,35,3,False
285,262,Mightyena,Dark,NaN,420,70,90,70,60,60,70,3,False
326,302,Sableye,Dark,Ghost,380,50,75,75,65,65,50,3,False
327,302,SableyeMega Sableye,Dark,Ghost,480,50,85,125,85,115,20,3,False
666,605,Elgyem,Psychic,NaN,335,55,55,55,85,55,30,5,False
667,606,Beheeyem,Psychic,NaN,485,75,75,75,125,95,40,5,False

In [44]:
df.loc[df['Name'].str.contains('Sableye') & (df['Total'] > 390)]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
327,302,SableyeMega Sableye,Dark,Ghost,480,50,85,125,85,115,20,3,False

In [45]:
df.loc[df['Name'].str.contains('Houndoom')]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
247,229,Houndoom,Dark,Fire,500,75,90,50,110,80,95,2,False
248,229,HoundoomMega Houndoom,Dark,Fire,600,75,90,90,140,90,115,2,False

In [46]:
df.loc[~df['Name'].str.contains('Houndoom')][0:5]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

In [47]:
import re
df.loc[df['Type 1'].str.contains('Grass|Ghost', regex = True)]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
48,43,Oddish,Grass,Poison,320,45,50,55,75,65,30,1,False
49,44,Gloom,Grass,Poison,395,60,65,70,85,75,40,1,False
50,45,Vileplume,Grass,Poison,490,75,80,85,110,90,50,1,False
75,69,Bellsprout,Grass,Poison,300,50,75,35,70,30,40,1,False
76,70,Weepinbell,Grass,Poison,390,65,90,50,85,45,55,1,False
77,71,Victreebel,Grass,Poison,490,80,105,65,100,70,70,1,False
99,92,Gastly,Ghost,Poison,310,30,35,30,100,35,80,1,False
100,93,Haunter,Ghost,Poison,405,45,50,45,115,55,95,1,False
101,94,Gengar,Ghost,Poison,500,60,65,60,130,75,110,1,False
102,94,GengarMega Gengar,Ghost,Poison,600,60,65,80,170,95,130,1,False
110,102,Exeggcute,Grass,Psychic,325,60,40,80,60,45,40,1,False
111,103,Exeggutor,Grass,Psychic,520,95,95,85,125,65,55,1,False
122,114,Tangela,Grass,NaN,435,65,55,115,100,40,60,1,False
166,152,Chikorita,Grass,NaN,318,45,49,65,49,65,45,2,False
167,153,Bayleef,Grass,NaN,405,60,62,80,63,80,60,2,False
168,154,Meganium,Grass,NaN,525,80,82,100,83,100,80,2,False
197,182,Bellossom,Grass,NaN,490,75,80,95,90,100,50,2,False
202,187,Hoppip,Grass,Flying,250,35,35,40,35,55,50,2,False
203,188,Skiploom,Grass,Flying,340,55,45,50,45,65,80,2,False
204,189,Jumpluff,Grass,Flying,460,75,55,70,55,95,110,2,False
206,191,Sunkern,Grass,NaN,180,30,30,30,30,30,30,2,False
207,192,Sunflora,Grass,NaN,425,75,75,55,105,85,30,2,False
215,200,Misdreavus,Ghost,NaN,435,60,60,60,85,85,85,2,False
272,252,Treecko,Grass,NaN,310,40,45,35,65,55,70,3,False
273,253,Grovyle,Grass,NaN,405,50,65,45,85,65,95,3,False
274,254,Sceptile,Grass,NaN,530,70,85,65,105,85,120,3,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
606,546,Cottonee,Grass,Fairy,280,40,27,60,37,50,66,5,False
607,547,Whimsicott,Grass,Fairy,480,60,67,85,77,75,116,5,False
608,548,Petilil,Grass,NaN,280,45,35,50,70,50,30,5,False
609,549,Lilligant,Grass,NaN,480,70,60,75,110,75,90,5,False
617,556,Maractus,Grass,NaN,461,75,86,67,106,67,60,5,False
623,562,Yamask,Ghost,NaN,303,38,30,85,55,65,30,5,False
624,563,Cofagrigus,Ghost,NaN,483,58,50,145,95,105,30,5,False
651,590,Foongus,Grass,Poison,294,69,55,45,55,55,15,5,False
652,591,Amoonguss,Grass,Poison,464,114,85,70,85,80,30,5,False
658,597,Ferroseed,Grass,Steel,305,44,50,91,24,86,10,5,False
659,598,Ferrothorn,Grass,Steel,489,74,94,131,54,116,20,5,False
668,607,Litwick,Ghost,Fire,275,50,30,55,65,55,20,5,False
669,608,Lampent,Ghost,Fire,370,60,40,60,95,60,55,5,False
670,609,Chandelure,Ghost,Fire,520,60,55,90,145,90,80,5,False
701,640,Virizion,Grass,Fighting,580,91,90,72,90,129,108,5,True
718,650,Chespin,Grass,NaN,313,56,61,65,48,45,38,6,False
719,651,Quilladin,Grass,NaN,405,61,78,95,56,58,57,6,False
720,652,Chesnaught,Grass,Fighting,530,88,107,122,74,75,64,6,False
740,672,Skiddo,Grass,NaN,350,66,65,48,62,57,52,6,False
741,673,Gogoat,Grass,NaN,531,123,100,62,97,81,68,6,False
778,708,Phantump,Ghost,Grass,309,43,70,48,50,60,38,6,False
779,709,Trevenant,Ghost,Grass,474,85,110,76,65,82,56,6,False
780,710,PumpkabooAverage Size,Ghost,Grass,335,49,66,70,44,55,51,6,False
781,710,PumpkabooSmall Size,Ghost,Grass,335,44,66,70,44,55,56,6,False
782,710,PumpkabooLarge Size,Ghost,Grass,335,54,66,70,44,55,46,6,False
783,710,PumpkabooSuper Size,Ghost,Grass,335,59,66,70,44,55,41,6,False
784,711,GourgeistAverage Size,Ghost,Grass,494,65,90,122,58,75,84,6,False
785,711,GourgeistSmall Size,Ghost,Grass,494,55,85,122,58,75,99,6,False
786,711,GourgeistLarge Size,Ghost,Grass,494,75,95,122,58,75,69,6,False
787,711,GourgeistSuper Size,Ghost,Grass,494,85,100,122,58,75,54,6,False

In [48]:
df.loc[df['Type 1'].str.contains('poison|flying', flags = re.I, regex=True)]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
28,23,Ekans,Poison,NaN,288,35,60,44,40,54,55,1,False
29,24,Arbok,Poison,NaN,438,60,85,69,65,79,80,1,False
34,29,Nidoran♀,Poison,NaN,275,55,47,52,40,40,41,1,False
35,30,Nidorina,Poison,NaN,365,70,62,67,55,55,56,1,False
36,31,Nidoqueen,Poison,Ground,505,90,92,87,75,85,76,1,False
37,32,Nidoran♂,Poison,NaN,273,46,57,40,40,40,50,1,False
38,33,Nidorino,Poison,NaN,365,61,72,57,55,55,65,1,False
39,34,Nidoking,Poison,Ground,505,81,102,77,85,75,85,1,False
46,41,Zubat,Poison,Flying,245,40,45,35,30,40,55,1,False
47,42,Golbat,Poison,Flying,455,75,80,70,65,75,90,1,False
95,88,Grimer,Poison,NaN,325,80,80,50,40,50,25,1,False
96,89,Muk,Poison,NaN,500,105,105,75,65,100,50,1,False
117,109,Koffing,Poison,NaN,340,40,65,95,60,45,35,1,False
118,110,Weezing,Poison,NaN,490,65,90,120,85,70,60,1,False
183,169,Crobat,Poison,Flying,535,85,90,80,70,80,130,2,False
345,316,Gulpin,Poison,NaN,302,70,43,53,43,53,40,3,False
346,317,Swalot,Poison,NaN,467,100,73,83,73,83,55,3,False
368,336,Seviper,Poison,NaN,458,73,100,60,100,60,65,3,False
482,434,Stunky,Poison,Dark,329,63,63,47,41,41,74,4,False
483,435,Skuntank,Poison,Dark,479,103,93,67,71,61,84,4,False
501,451,Skorupi,Poison,Bug,330,40,50,90,30,55,65,4,False
502,452,Drapion,Poison,Dark,500,70,90,110,60,75,95,4,False
503,453,Croagunk,Poison,Fighting,300,48,61,40,61,40,50,4,False
504,454,Toxicroak,Poison,Fighting,490,83,106,65,86,65,85,4,False
629,568,Trubbish,Poison,NaN,329,50,50,62,40,62,65,5,False
630,569,Garbodor,Poison,NaN,474,80,95,82,60,82,75,5,False
702,641,TornadusIncarnate Forme,Flying,NaN,580,79,115,70,125,80,111,5,True
703,641,TornadusTherian Forme,Flying,NaN,580,79,100,80,110,90,121,5,True
760,690,Skrelp,Poison,Water,320,50,60,60,60,60,30,6,False
761,691,Dragalge,Poison,Dragon,494,65,75,90,97,123,44,6,False
790,714,Noibat,Flying,Dragon,245,40,30,35,45,40,55,6,False
791,715,Noivern,Flying,Dragon,535,85,70,80,97,80,123,6,False

**Conditional changes**

In [49]:
df.head(5)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

In [50]:
df.loc[df['Type 1'] == 'Grass', 'Type 1'] = 'Poison'
df.head(5)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Poison,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Poison,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Poison,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Poison,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

In [51]:
df.loc[df['Type 1'] == 'Poison', 'Type 1'] = 'Grass'
df.head(5)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

In [52]:
df.loc[df['HP'] >= 50, ['Total', 'Attack']] = 'Test0'
df.head(5)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,Test0,60,Test0,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,Test0,80,Test0,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,Test0,80,Test0,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

In [53]:
df.loc[df['Total'] == 'Test0', ['Total', 'Attack']] = [12, 45]
df.head(5)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,12,60,45,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,12,80,45,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,12,80,45,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

In [54]:
df.loc[df['Total'] == 12, ['Total', 'Attack']] = [2, 5]
df.head(5)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,2,60,5,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,2,80,5,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,2,80,5,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

**Group by - mean**

In [55]:
df.groupby('Type 1').mean()

,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Type 1,,,,,,,,,,
Bug,334.492754,72.043478,56.884058,14.550725,70.724638,53.869565,64.797101,61.681159,3.217391,0.000000
Dark,461.354839,50.096774,66.806452,14.354839,70.225806,74.645161,69.516129,76.161290,4.032258,0.064516
Dragon,474.375000,39.875000,83.312500,13.000000,86.375000,96.843750,88.843750,83.031250,3.875000,0.375000
Electric,363.500000,68.750000,59.795455,14.909091,66.295455,90.022727,73.704545,84.500000,3.272727,0.090909
Fairy,449.529412,34.000000,74.117647,7.823529,65.705882,78.529412,84.705882,48.588235,4.117647,0.058824
Fighting,363.851852,54.592593,69.851852,15.555556,65.925926,53.111111,64.703704,66.074074,3.370370,0.000000
Fire,327.403846,48.961538,69.903846,12.365385,67.769231,88.980769,72.211538,74.442308,3.211538,0.096154
Flying,677.750000,62.750000,70.750000,11.250000,66.250000,94.250000,72.500000,102.500000,5.500000,0.500000
Ghost,486.500000,112.843750,64.437500,22.250000,81.187500,79.343750,76.468750,64.343750,4.187500,0.062500
Grass,318.275510,56.918367,67.265306,12.785714,70.234694,72.622449,68.704082,62.397959,3.122449,0.030612
Ground,356.281250,41.125000,73.781250,12.968750,84.843750,56.468750,62.750000,63.906250,3.156250,0.125000
Ice,423.541667,40.916667,72.000000,10.000000,71.416667,77.541667,76.291667,63.458333,3.541667,0.083333
Normal,319.173469,45.438776,77.275510,12.561224,59.846939,55.816327,63.724490,71.551020,3.051020,0.020408
Psychic,380.807018,62.614035,70.631579,11.000000,67.684211,98.403509,86.280702,81.491228,3.385965,0.245614
Rock,392.727273,64.840909,65.363636,14.977273,100.795455,63.340909,75.477273,55.909091,3.454545,0.090909
Steel,442.851852,36.037037,65.222222,11.481481,126.370370,67.518519,80.629630,55.259259,3.851852,0.148148
Water,303.089286,55.223214,72.062500,13.026786,72.946429,74.812500,70.517857,65.964286,2.857143,0.035714

In [56]:
df.groupby('Type 1').mean().sort_values('HP', ascending = False)

,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Type 1,,,,,,,,,,
Dragon,474.375000,39.875000,83.312500,13.000000,86.375000,96.843750,88.843750,83.031250,3.875000,0.375000
Normal,319.173469,45.438776,77.275510,12.561224,59.846939,55.816327,63.724490,71.551020,3.051020,0.020408
Fairy,449.529412,34.000000,74.117647,7.823529,65.705882,78.529412,84.705882,48.588235,4.117647,0.058824
Ground,356.281250,41.125000,73.781250,12.968750,84.843750,56.468750,62.750000,63.906250,3.156250,0.125000
Water,303.089286,55.223214,72.062500,13.026786,72.946429,74.812500,70.517857,65.964286,2.857143,0.035714
Ice,423.541667,40.916667,72.000000,10.000000,71.416667,77.541667,76.291667,63.458333,3.541667,0.083333
Flying,677.750000,62.750000,70.750000,11.250000,66.250000,94.250000,72.500000,102.500000,5.500000,0.500000
Psychic,380.807018,62.614035,70.631579,11.000000,67.684211,98.403509,86.280702,81.491228,3.385965,0.245614
Fire,327.403846,48.961538,69.903846,12.365385,67.769231,88.980769,72.211538,74.442308,3.211538,0.096154
Fighting,363.851852,54.592593,69.851852,15.555556,65.925926,53.111111,64.703704,66.074074,3.370370,0.000000
Grass,318.275510,56.918367,67.265306,12.785714,70.234694,72.622449,68.704082,62.397959,3.122449,0.030612
Dark,461.354839,50.096774,66.806452,14.354839,70.225806,74.645161,69.516129,76.161290,4.032258,0.064516
Rock,392.727273,64.840909,65.363636,14.977273,100.795455,63.340909,75.477273,55.909091,3.454545,0.090909
Steel,442.851852,36.037037,65.222222,11.481481,126.370370,67.518519,80.629630,55.259259,3.851852,0.148148
Ghost,486.500000,112.843750,64.437500,22.250000,81.187500,79.343750,76.468750,64.343750,4.187500,0.062500
Electric,363.500000,68.750000,59.795455,14.909091,66.295455,90.022727,73.704545,84.500000,3.272727,0.090909
Bug,334.492754,72.043478,56.884058,14.550725,70.724638,53.869565,64.797101,61.681159,3.217391,0.000000

In [57]:
df.groupby('Type 2').mean().sort_values('Attack', ascending = False)

,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Type 2,,,,,,,,,,
Bug,382.000000,229.000000,53.333333,50.000000,80.000000,46.666667,61.666667,61.666667,3.333333,0.000000
Grass,505.400000,73.280000,62.640000,18.000000,80.120000,60.160000,74.520000,57.320000,4.480000,0.000000
Water,400.000000,93.214286,62.714286,18.000000,85.071429,74.500000,68.642857,57.142857,3.428571,0.071429
Poison,169.970588,96.588235,58.764706,17.323529,59.558824,74.029412,69.911765,66.647059,1.970588,0.000000
Ghost,551.714286,41.785714,59.142857,16.428571,82.285714,73.214286,78.071429,53.857143,4.785714,0.071429
Steel,435.636364,61.636364,64.636364,13.727273,104.636364,77.727273,86.272727,59.363636,3.818182,0.045455
Normal,681.000000,73.750000,63.500000,13.250000,53.750000,88.000000,64.250000,89.250000,6.000000,0.000000
Flying,331.103093,44.938144,71.391753,11.185567,68.309278,75.628866,71.206186,85.721649,3.072165,0.134021
Fairy,379.043478,67.913043,64.304348,10.739130,73.869565,75.000000,81.956522,61.217391,3.565217,0.086957
Fire,481.833333,29.333333,71.250000,9.583333,80.166667,110.416667,83.500000,79.666667,4.000000,0.250000
Ground,307.600000,29.000000,77.228571,9.428571,90.314286,65.542857,66.742857,54.657143,2.942857,0.028571
Psychic,337.151515,37.666667,72.212121,9.393939,87.030303,88.030303,87.606061,69.484848,2.939394,0.151515
Dark,413.850000,17.150000,75.550000,9.250000,72.050000,81.800000,69.850000,75.350000,3.750000,0.050000
Fighting,438.192308,13.461538,79.461538,7.153846,82.500000,81.269231,82.384615,87.384615,3.923077,0.153846
Dragon,482.555556,15.500000,82.166667,6.388889,87.055556,98.500000,83.444444,80.555556,4.166667,0.222222
Rock,347.785714,37.928571,68.071429,5.357143,126.857143,51.142857,68.571429,36.000000,3.142857,0.000000
Electric,465.666667,2.000000,88.166667,5.000000,68.333333,81.166667,73.500000,71.500000,4.000000,0.166667
Ice,441.285714,2.000000,90.000000,5.000000,85.642857,92.642857,84.785714,74.642857,3.714286,0.214286

**Group by - sum**

In [58]:
df.groupby('Type 1').sum()

,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Type 1,,,,,,,,,,
Bug,23080,4971,3925,1004,4880,3717,4471,4256,222,0.0
Dark,14302,1553,2071,445,2177,2314,2155,2361,125,2.0
Dragon,15180,1276,2666,416,2764,3099,2843,2657,124,12.0
Electric,15994,3025,2631,656,2917,3961,3243,3718,144,4.0
Fairy,7642,578,1260,133,1117,1335,1440,826,70,1.0
Fighting,9824,1474,1886,420,1780,1434,1747,1784,91,0.0
Fire,17025,2546,3635,643,3524,4627,3755,3871,167,5.0
Flying,2711,251,283,45,265,377,290,410,22,2.0
Ghost,15568,3611,2062,712,2598,2539,2447,2059,134,2.0
Grass,31191,5578,6592,1253,6883,7117,6733,6115,306,3.0
Ground,11401,1316,2361,415,2715,1807,2008,2045,101,4.0
Ice,10165,982,1728,240,1714,1861,1831,1523,85,2.0
Normal,31279,4453,7573,1231,5865,5470,6245,7012,299,2.0
Psychic,21706,3569,4026,627,3858,5609,4918,4645,193,14.0
Rock,17280,2853,2876,659,4435,2787,3321,2460,152,4.0
Steel,11957,973,1761,310,3412,1823,2177,1492,104,4.0
Water,33946,6185,8071,1459,8170,8379,7898,7388,320,4.0

**Group by - count**

In [59]:
df.groupby('Type 1').count()

,#,Name,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Type 1,,,,,,,,,,,,
Bug,69,69,52,69,69,69,69,69,69,69,69,69
Dark,31,31,21,31,31,31,31,31,31,31,31,31
Dragon,32,32,21,32,32,32,32,32,32,32,32,32
Electric,44,44,17,44,44,44,44,44,44,44,44,44
Fairy,17,17,2,17,17,17,17,17,17,17,17,17
Fighting,27,27,7,27,27,27,27,27,27,27,27,27
Fire,52,52,24,52,52,52,52,52,52,52,52,52
Flying,4,4,2,4,4,4,4,4,4,4,4,4
Ghost,32,32,22,32,32,32,32,32,32,32,32,32
Grass,98,98,50,98,98,98,98,98,98,98,98,98
Ground,32,32,19,32,32,32,32,32,32,32,32,32
Ice,24,24,11,24,24,24,24,24,24,24,24,24
Normal,98,98,37,98,98,98,98,98,98,98,98,98
Psychic,57,57,19,57,57,57,57,57,57,57,57,57
Rock,44,44,35,44,44,44,44,44,44,44,44,44
Steel,27,27,22,27,27,27,27,27,27,27,27,27
Water,112,112,53,112,112,112,112,112,112,112,112,112

In [60]:
df['Count'] = 1
df.groupby(['Type 1']).count()['Count']

Type 1
Bug          69
Dark         31
Dragon       32
Electric     44
Fairy        17
Fighting     27
Fire         52
Flying        4
Ghost        32
Grass        98
Ground       32
Ice          24
Normal       98
Psychic      57
Rock         44
Steel        27
Water       112
Name: Count, dtype: int64

In [61]:
df['Count'] = 1
df.groupby(['Type 1', 'Type 2']).count()['Count']

Type 1  Type 2
Bug     Electric     2
        Fighting     2
        Fire         2
        Flying      14
        Ghost        1
                    ..
Water   Ice          3
        Poison       3
        Psychic      5
        Rock         4
        Steel        1
Name: Count, Length: 131, dtype: int64

**To be countinued...!**